### ISSUE TITLE
Dataset setting issues

### ISSUE THREAD

**Issue by landingu** [martianxiu/DS-Net#1]
May I ask why the author set more data (about 50%) for testing instead of training？

**Comment by martianxiu** [comment]
Hello! Thank you for your question. The high test ratio was chosen to reflect a practical scenario. In the event of an earthquake, damage detection systems may need to be deployed immediately, leaving little time to create a large dataset.

**Comment by landingu** [comment]
That's really reasonable！Thank you very much for your reply and your excellent work!
